import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Hunting Coders</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <div className={styles.heading}>
          <h1>&lt; Hunting Coders / &gt;</h1>
          <p>A blog for Coders by Coders</p>
          <Image className={styles.headingImg} src="/homeimg.jpg" alt='' width={237} height={158} />
          {/* <img className={styles.headingImg} src="/homeimg.jpg" alt='' width={237} height={158} /> */}
        </div>
        <div className={styles.blogs}>
          <h2>Popular Blogs</h2>
          <div className={styles.blogItem}>
            <h3>How to learn HTML</h3>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Corrupti autem consequuntur, maiores ratione quas beatae?</p>
          </div>
          <div className={styles.blogItem}>
            <h3>How to learn CSS</h3>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Corrupti autem consequuntur, maiores ratione quas beatae?</p>
          </div>
          <div className={styles.blogItem}>
            <h3>How to learn JavaScript</h3>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Corrupti autem consequuntur, maiores ratione quas beatae?</p>
          </div>
        </div>
      </div>
    </>
  )
}
